### ISSUE TITLE
Small fixes in pom.xml

### ISSUE THREAD

**Issue by stefan2904** [a-sit/PDF-Over#24]
- [x] Fix `<developers>`
https://github.com/a-sit/PDF-Over/blob/593173d19dcedd5a01eaf6aae322ce918e703165/pom.xml#L20-L61

- [x] Fix `<url>` (`http://a-sit.at` does not work, `https://www.a-sit.at` does)
- [x] Fix `<scm>` (now github) 
- [x] Fix `<issueManagement>` (this seems very old?)
- [ ] Check/fix `<repositories>` (`https://apps.egiz.gv.at` maven repo seems dead)

**Comment by iaik-jheher** [comment]
`<repositories>` issue is known, `maven-snapshot` is not reachable externally. Removal is in progress.

**Comment by iaik-jheher** [comment]
`<repositories>` issue superseded by #26
