### ISSUE TITLE
Integrate updated profile for academic titles

### ISSUE THREAD

**Issue by asitadmin** [a-sit/PDF-Over#47]
Please swap the BASE_NORMAL.properties file ind the pdf-as cfg with this one (and rm the .txt).
[BASE_NORMAL.properties.txt](https://github.com/a-sit/PDF-Over/files/10175583/BASE_NORMAL.properties.txt)

**Comment by iaik-jheher** [comment]
I want to use this as the impetus to finally work on #6, since I doubt that's ever getting done on its own...
