### ISSUE TITLE
4.4.4 still says "Update to 4.4.4 avail." after install

### ISSUE THREAD

**Issue by michaelof** [a-sit/PDF-Over#64]
PDF-Over 4.4.4 
OpenSUSE 15.4 (LINUX, Wayland)

Small issue.

Steps processed:
- As installer said "incompatible version" when trying to upgrade directly from 4.3.2-1, performed a "java -jar Uninstaller.jar" and wiped folder ~/PDF-Over, to be sure
- installed 4.4.4.

Popup (still) appears on each startup of PDF-Over.

**Comment by iaik-jheher** [comment]
What version is listed in the window title if you open the settings dialog?

**Comment by michaelof** [comment]
My Mistake, sorry, somehow installed 4.4.0 instead of 4.4.4. Issue can be CLOSED
