### ISSUE TITLE
Incorrect credentials Error with correct credentials

### ISSUE THREAD

**Issue by iaik-skeller** [a-sit/PDF-Over#67]
(see mail "Re: AW: AW: AW: PDF Over funktioniert nicht mehr" 15.01.2023)
For a yet unknown reason a few users (3 so far) receive the incorrect credentials error, when the communication starts with A-Trust
![20230104_210743](https://user-images.githubusercontent.com/120659400/212930091-515a73bf-53ec-4990-8840-2b716a07312b.jpg)
All three users did verify the functionality of their credentials with the demo login.
The user reported 4.4.1 as the latest working version of PDF-Over.
**Note:** A phonenumber and Handysignature is used at least in 1 of the cases.

**Todo** Investigate changes from 4.4.1 to 4.4.2 that could have influenced what we're sending to A-Trust for authentication.
Stay in touch with the affected users, as we atm cannot reproduce the behaviour.

For the log: This was caused by special characters in the password

**Comment by iaik-jheher** [comment]
was 4.4.2 the atrust rewrite, or was that 4.4.3? have we verified that it's broken in 4.4.2 as well?

**Comment by iaik-skeller** [comment]
Successfully tested on

- [ ] Windows
- [ ] Mac
- [ ] Linux

**Comment by tstrohmeier** [comment]
I have the same Issue with pdf-over v.4.4.4 on MacOS (x64).

<img width="598" alt="Bildschirm­foto 2023-02-22 um 16 54 33" src="https://user-images.githubusercontent.com/13830953/220679827-c2d6e624-17e4-4cdc-84d5-7763ec529e5a.png">

**Comment by iaik-jheher** [comment]
The issue we found to likely be causing this is incorrect UTF-8 encoding in form submissions. Any characters outside the base ASCII 0-127 range will cause the issue, such as Umlauts.

If this affects you, you can grab the PR CI build from #73 as a temporary workaround until we manage to roll this out as a proper release.
