### ISSUE TITLE
State machine error with additional (non-placeholder) QR code 

### ISSUE THREAD

**Issue by iaik-skeller** [a-sit/PDF-Over#77]
Reported and reproduced on Linux.
Not reproduceable under Windows atm, perhaps only on Linux (eventually Mac).

## Steps to Reproduce

1. Open PDF with QR placeholder and other QR code.
[corrupted_small_de.pdf](https://github.com/a-sit/PDF-Over/files/10725319/corrupted_small_de.pdf)
2. Sign through cmd line
3. Chose to use placeholder
4. Enter credentials
6. `ERROR | main @ a.asit.pdfover.gui.workflow.StateMachine | StateMachine
update:
java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(SWT.java:4899)`

## Expected Behavior

Correct placeholder should be used for positioning

## Current Behavior

Error occurs and signature is placed with p: auto instead.

**Comment by rarzberger4** [comment]
Also reproducible with only the placeholder qr-code like in #78?

**Comment by iaik-jheher** [comment]
re-test after #80 please

**Comment by iaik-jheher** [comment]
I cannot reproduce after #80.
