### ISSUE TITLE
Automatic placeholder search broken using linux command line

### ISSUE THREAD

**Issue by rarzberger4** [a-sit/PDF-Over#78]
## Steps to Reproduce

1. pdf-over 4.4.4 installed on ubuntu 22.04.2 LTS
2. open pdf-over
3. change the settings inside the gui to automatic positioning of the signature and activate placeholder-qr-code search
4. reopen pdf-over using: "sh pdf-over_linux.sh -i signatur_Test.pdf -a" using -a or not is not relevant for the crash to occur
5. a menu pops up and select anything --> crash

## Expected Behavior

Expected to put the signature on the placeholder qr-code automatically so only thing to do is authorize the signature

## Current Behavior

The program reports a found qr-placeholder

![2023-03-01 11_44_16-192 168 2 196 (rarzberger)](https://user-images.githubusercontent.com/91483040/222139045-fcc45b19-de43-4e27-af2b-1b020454c8f6.png)

If you click any option the program crashes
![2023-03-01 11_44_35-PDF-Over @ubuntutest](https://user-images.githubusercontent.com/91483040/222139156-063e836b-df37-4b71-83f2-5b2634100563.png)

Error in the command line after crashing:
![2023-03-01 11_45_07-192 168 2 196 (rarzberger)](https://user-images.githubusercontent.com/91483040/222139239-be24f4ca-2266-46dc-96dd-03dae80da513.png)

But if you open pdf-over with default config and set the placeholder search like in step 3. and then use the file browser to select a document the placeholder works as expected.

**Comment by iaik-jheher** [comment]
possibly dup #77?

**Comment by rarzberger4** [comment]
probably the same problem, but it would be interesting if the error occured also for #77 if onyl the placeholder qr-code is used without a second one

**Comment by rarzberger4** [comment]
So it seems that not the automatic placeholder is the problem. If i run pdf-over without a invalid argument: "sh pdf-over_linux.sh -i" then this happens:
![image](https://user-images.githubusercontent.com/91483040/222694629-37fe3a22-ea5b-4118-8ffd-0d1515b1539e.png)

If I set a argument for a valid path but not a pdf-file:  "sh pdf-over_linux.sh -i /home/rarzberger/PDF-Over/toSign/"
this happens:
![image](https://user-images.githubusercontent.com/91483040/222695157-be3ea0fb-ddcf-4def-af87-d65976efc535.png)

The same Error is written in the cli:
![image](https://user-images.githubusercontent.com/91483040/222695735-591c4030-ad9e-4d16-a4ed-5726c6a4da2b.png)


The problem occurs when a GUI menu appears automatically before I do anything in the program itself. The menu has no valid actions. It doesn't matter what menu-item I click, the program crashes.

**Comment by rarzberger4** [comment]
Error does not appear on windows.

**Comment by iaik-jheher** [comment]
Is "check for updates" enabled (in the "about" tab of the configuration)?

**Comment by rarzberger4** [comment]
Yes is activated

**Comment by iaik-jheher** [comment]
Managed to reproduce.

**Comment by iaik-jheher** [comment]
PR #80 referenced above should address this. If you could quickly check that it also works for you, that'd be appreciated.

Lightweight CI builds for the PR are available in the PR comments.

**Comment by rarzberger4** [comment]
Tested the builds an the problem is gone - thank you
