### ISSUE TITLE
Linux CLI Only

### ISSUE THREAD

**Issue by rarzberger4** [a-sit/PDF-Over#81]
I would like to do the whole signature process using the CLI in Linux without the need of a GUI.

This would help a lot if you want to create a internal workflow for signing documents, because an simple api could be created and no screen forwarding in any way is needed.

Since the use of start-commands is already possible and the config file is open to config via an editor, the only thing that is missing is to provide the comparison value for the user and an input if SMS is used. Everything else works without the GUI already.

Additional: I have not tested a token and so I don't know how this would work out for a CLI-based workflow.

**Comment by iaik-jheher** [comment]
If you're looking to fully automate signatures, I'm not sure if PDF-Over is the right place to look.

Meanwhile, the underlying [PDF-AS library](https://technology.a-sit.at/en/pdf-as/) is the tool that's actually designed to do what you are looking to do.

**Comment by rarzberger4** [comment]
Ok because PDF-Over seems quiet easy and straight forward to use and offers all the functionality that I need.

But I will have a look into the PDF-AS library thank you!
