### ISSUE TITLE
Closing and re-opening settings dialog resets signature profile

### ISSUE THREAD

**Issue by stefan2904** [a-sit/PDF-Over#90]
Using PDF over 4.4.5 on Ubuntu

## Steps to Reproduce

1. Open the settings dialog
2. Configure a custom signature profile, e.g., "nur Bildmarke" 
3. Close settings dialog by pressing "Save"
4. Open settings dialog again 

## Expected Behavior

Signature profile I selected ("nur Bildmarke") is still selected.

## Current Behavior

Standard signature profile ("Standard Signaturblock") is selected.

**Comment by stefan2904** [comment]
Nothing exciting in the log.

`SIGNATURE_PROFILE=BASE_LOGO` is correctly set in the config.

**Comment by iaik-jheher** [comment]
I can reproduce this.
